import sqlite3
conn = sqlite3.connect('backend/database.db')
cursor = conn.cursor()
cursor.execute('SELECT name FROM sqlite_master WHERE type="table"')
print('Tables:', cursor.fetchall())
cursor.execute('SELECT COUNT(*) FROM establishments')
print('Establishments:', cursor.fetchone()[0])
cursor.execute('SELECT COUNT(*) FROM cases_7a')
print('Cases:', cursor.fetchone()[0])
cursor.execute('SELECT COUNT(*) FROM redbook')
print('Redbook:', cursor.fetchone()[0])
cursor.execute('SELECT COUNT(*) FROM hearing_log')
print('Hearings:', cursor.fetchone()[0])
conn.close()